#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

$birthDate = '1983-09-30';
$days = new \Anatskyi\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n ";
