#!/usr/bin/env php
<?php

include "src/Dates/BirthDays.php";

$birthDate = "1983-09-30";
$days = new \Anatskyi\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n ";
